/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonClick: typeof import('./src/components/ButtonClick.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    IconsMdiClipboardArrowDown: typeof import('~icons/mdi/clipboard-arrow-down')['default']
    IconsMdiClipboardFile: typeof import('~icons/mdi/clipboard-file')['default']
    IconsMdiCursorDefaultClick: typeof import('~icons/mdi/cursor-default-click')['default']
    IconsMdiFolder: typeof import('~icons/mdi/folder')['default']
    IconsMdiMessage: typeof import('~icons/mdi/message')['default']
    IconsMdiRestore: typeof import('~icons/mdi/restore')['default']
    IconsMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
  }
}
